<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<Platforms>x64</Platforms>
		<LangVersion>latest</LangVersion>
		<RootNamespace>AlianceGuard</RootNamespace>
		<AssemblyName>AlianceGuard</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DebugType>embedded</DebugType>
		<Optimize>true</Optimize>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DefineConstants>TRACE</DefineConstants>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="*.yml" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="System.Net.Http" />
	</ItemGroup>

  <ItemGroup>
	<PackageReference Include="ExMod.Exiled" Version="9.12.6" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  
</Project>